# Generated by Django 5.2.6 on 2025-10-20 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tarefa_data_conclusao'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioFoco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foco_nome', models.CharField(max_length=50, verbose_name='Nome do Foco')),
                ('descricao_curta', models.CharField(blank=True, max_length=100, verbose_name='Descrição Curta (Opcional)')),
                ('detalhes', models.TextField(verbose_name='Observações para a IA')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foco do Usuário',
                'verbose_name_plural': 'Focos do Usuário',
                'unique_together': {('user', 'foco_nome')},
            },
        ),
    ]
