# Generated by Django 5.2.6 on 2025-10-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_usuariofoco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariofoco',
            name='descricao_curta',
        ),
        migrations.AddField(
            model_name='usuariofoco',
            name='dados_especificos',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados Específicos do Foco'),
        ),
        migrations.AlterField(
            model_name='usuariofoco',
            name='detalhes',
            field=models.TextField(blank=True, verbose_name='Observações Adicionais (para a IA)'),
        ),
    ]
