# Generated by Django 5.2.6 on 2025-10-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_usuariofoco_descricao_curta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='xp',
            field=models.IntegerField(default=10, verbose_name='XP da Tarefa'),
        ),
    ]
