# Generated by Django 5.2.6 on 2025-10-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tarefa_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dias_foco',
            field=models.IntegerField(default=0, verbose_name='Dias de Foco (Streak)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_resgate_foco',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Resgate de Foco'),
        ),
    ]
