# Generated by Django 5.2.6 on 2025-10-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_usuario_dias_foco_usuario_ultimo_resgate_foco'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='xp_proximo_nivel',
            field=models.IntegerField(default=100, verbose_name='XP para o próximo nível'),
        ),
    ]
