# Generated by Django 5.2.6 on 2025-11-05 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usuario_xp_proximo_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='tipo_tarefa',
            field=models.CharField(choices=[('PESSOAL', 'Pessoal'), ('DIARIA', 'Diária'), ('SEMANAL', 'Semanal')], default='PESSOAL', max_length=10, verbose_name='Tipo da Tarefa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='xp_original',
            field=models.IntegerField(blank=True, null=True, verbose_name='XP Original (se falhou)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_reset_slots',
            field=models.DateField(default=datetime.date.today, verbose_name='Último dia que os slots foram resetados'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='slots_tarefas_pessoais_usados',
            field=models.IntegerField(default=0, verbose_name='Slots de tarefas pessoais usados hoje'),
        ),
    ]
