# Generated by Django 5.2.6 on 2025-11-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tarefa_tipo_tarefa_tarefa_xp_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='recorrente_dom',
            field=models.BooleanField(default=False, verbose_name='Dom'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='recorrente_qua',
            field=models.BooleanField(default=False, verbose_name='Qua'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='recorrente_qui',
            field=models.BooleanField(default=False, verbose_name='Qui'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='recorrente_sab',
            field=models.BooleanField(default=False, verbose_name='Sáb'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='recorrente_seg',
            field=models.BooleanField(default=False, verbose_name='Seg'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='recorrente_sex',
            field=models.BooleanField(default=False, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='recorrente_ter',
            field=models.BooleanField(default=False, verbose_name='Ter'),
        ),
    ]
