# Generated by Django 5.2.6 on 2025-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_tarefa_recorrente_dom_tarefa_recorrente_qua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='falhou',
            field=models.BooleanField(default=False, verbose_name='Tarefa Falhou (reset 22h)'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='frequencia',
            field=models.CharField(blank=True, choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], default='DIARIA', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='hora_lembrete',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário do Lembrete'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo_tarefa',
            field=models.CharField(choices=[('PESSOAL', 'Pessoal'), ('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('TEMPLATE_PESSOAL', 'Template Pessoal')], default='PESSOAL', max_length=20, verbose_name='Tipo da Tarefa'),
        ),
    ]
