# Generated by Django 5.2.6 on 2025-11-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_tarefa_falhou_alter_tarefa_frequencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_acao_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão ou Descarte'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='descartada',
            field=models.BooleanField(default=False, verbose_name='Tarefa Descartada'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tarefas_concluidas_atrasadas_count',
            field=models.IntegerField(default=0, verbose_name='Contador de tarefas concluídas (atrasadas)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tarefas_descartadas_count',
            field=models.IntegerField(default=0, verbose_name='Contador de tarefas descartadas'),
        ),
    ]
