# Generated by Django 5.2.6 on 2025-11-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_tarefa_data_acao_final_tarefa_descartada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tarefas_concluidas_prazo_count',
            field=models.IntegerField(default=0, verbose_name='Contador de tarefas concluídas (no prazo)'),
        ),
    ]
